//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcranAccueil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHETEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACHETEUR()
        {
            this.FICHE_DE_SOUHAITS = new HashSet<FICHE_DE_SOUHAITS>();
        }
    
        public short IDACHETEUR { get; set; }
        public short IDCOMMERCIAL { get; set; }
        public int IDVILLE { get; set; }
        public string NOM_ACHETEUR { get; set; }
        public string PRENOM_ACHETEUR { get; set; }
        public string ADRESSE { get; set; }
        public string EMAIL { get; set; }
        public int TÉLÉPHONE { get; set; }
        public int CODE_POSTAL { get; set; }
        public int TÉLÉPHONE_MOBILE { get; set; }
        public System.DateTime DATE_CREATION { get; set; }
    
        public virtual COMMERCIAL COMMERCIAL { get; set; }
        public virtual VILLE VILLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHE_DE_SOUHAITS> FICHE_DE_SOUHAITS { get; set; }
    }
}
