//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcranAccueil
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class basefinaleEntities : DbContext
    {
        public basefinaleEntities()
            : base("name=basefinaleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACHETEUR> ACHETEUR { get; set; }
        public virtual DbSet<BIEN> BIEN { get; set; }
        public virtual DbSet<COMMERCIAL> COMMERCIAL { get; set; }
        public virtual DbSet<FICHE_DE_SOUHAITS> FICHE_DE_SOUHAITS { get; set; }
        public virtual DbSet<PROPOSITION_VISITE> PROPOSITION_VISITE { get; set; }
        public virtual DbSet<RDV> RDV { get; set; }
        public virtual DbSet<VENDEUR> VENDEUR { get; set; }
        public virtual DbSet<VILLE> VILLE { get; set; }
    }
}
