//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcranAccueil
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHE_DE_SOUHAITS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FICHE_DE_SOUHAITS()
        {
            this.PROPOSITION_VISITE = new HashSet<PROPOSITION_VISITE>();
            this.VILLE1 = new HashSet<VILLE>();
        }
    
        public short IDFICHESOUHAITS { get; set; }
        public short IDACHETEUR { get; set; }
        public string STATUT { get; set; }
        public string VILLE { get; set; }
        public Nullable<int> SURFACE_PARCELLE { get; set; }
        public Nullable<int> SURFACE_HABITABLE { get; set; }
        public Nullable<int> NB_PIÈCE { get; set; }
        public Nullable<int> NB_CHAMBRES { get; set; }
        public Nullable<int> NB_SALLEDEBAIN { get; set; }
        public Nullable<bool> GARAGE { get; set; }
        public Nullable<bool> CAVE { get; set; }
        public int BUDGET { get; set; }
    
        public virtual ACHETEUR ACHETEUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPOSITION_VISITE> PROPOSITION_VISITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VILLE> VILLE1 { get; set; }
    }
}
