//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcranAccueil
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDV
    {
        public short IDRDV { get; set; }
        public short IDVISITE { get; set; }
    
        public virtual PROPOSITION_VISITE PROPOSITION_VISITE { get; set; }
    }
}
