//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcranAccueil
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENDEUR()
        {
            this.BIEN = new HashSet<BIEN>();
        }
    
        public short IDVENDEUR { get; set; }
        public int IDVILLE { get; set; }
        public string NOM_VENDEUR { get; set; }
        public string PRÉNOM_VENDEUR { get; set; }
        public string ADRESSE_VENDEUR { get; set; }
        public int TÉLÉPHONE_FIXE { get; set; }
        public Nullable<int> TÉLÉPHONE_MOBILE { get; set; }
        public string EMAIL { get; set; }
        public int CODE_POSTAL { get; set; }
        public System.DateTime DATE_CREATION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIEN> BIEN { get; set; }
        public virtual VILLE VILLE { get; set; }
    }
}
